### ISSUE TITLE
Ideas for patch

### ISSUE THREAD

**Issue by mruiz1991** [mruiz1991/Tafe17S203#4]
Add any ideas for a patch on here

**Comment by mruiz1991** [comment]
Have the title say "Group 3" with different coloured background

**Comment by mruiz1991** [comment]
Change the splash screen?

**Comment by aannoo** [comment]
I like that idea Martin but I think that is too complex. Lets just change one line of text somewhere inconsequential.

**Comment by mruiz1991** [comment]
Rightio

**Comment by uberaty** [comment]
we can change fontsize or font color of the main page

**Comment by aannoo** [comment]
Ok guys everybody else's ideas are terrible!
What about this (great) idea: Lets change the about page to include information about our team.
I'll get right on to that!
